name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Dashboard code
      uses: actions/checkout@v2
    - name: Setup Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Reuse Cache
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install package && build
      run: |
        yarn
        yarn build
        cp ext_resource/* dist/
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'clash-dashboard.zip'
        path: './*'
        directory: 'dist/'
    - name: release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "auto build for chrome extension"
        files: |
          dist/clash-dashboard.zip
